CREATE TABLE products (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255) NOT NULL,
    price               NUMERIC(19, 2) NOT NULL CHECK ( price > 0 ),
    stock_quantity      INT NOT NULL CHECK ( stock_quantity >= 0 ),
    created_at          TIMESTAMP NOT NULL,
    version             BIGINT NOT NULL DEFAULT 0
);