CREATE TABLE carts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    status     VARCHAR(20)                             NOT NULL DEFAULT 'ACTIVE',
    version    BIGINT                                  NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),

    CONSTRAINT pk_carts PRIMARY KEY (id),

    CONSTRAINT uq_carts_user UNIQUE (user_id),

    CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

ALTER TABLE carts
    ADD CONSTRAINT chk_cart_status
        CHECK ( status IN ('ACTIVE', 'CHECKED_OUT', 'EXPIRED'));

CREATE TABLE cart_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id    BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    quantity   INTEGER                                 NOT NULL CHECK ( quantity > 0 ),
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),

    CONSTRAINT pk_cart_items PRIMARY KEY (id),

    CONSTRAINT fk_cart_items_cart
        FOREIGN KEY (cart_id)
            REFERENCES carts (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_cart_items_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
            ON DELETE RESTRICT,

    CONSTRAINT uq_cart_items_cart_product
        UNIQUE (cart_id, product_id)
);

CREATE INDEX idx_carts_user_id ON carts(user_id);

CREATE INDEX idx_cart_items_cart_id ON cart_items(cart_id);

CREATE INDEX idx_cart_items_product_id ON cart_items(product_id);