CREATE TABLE inventory_reservations
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id      BIGINT                                  NOT NULL,
    order_id        BIGINT                                  NOT NULL,
    quantity        INTEGER                                 NOT NULL CHECK ( quantity > 0 ),
    status          VARCHAR(20)                             NOT NULL,
    idempotency_key VARCHAR(100)                            NOT NULL,
    version         BIGINT                                  NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),

    CONSTRAINT pk_inventory_reservations PRIMARY KEY (id),

    CONSTRAINT fk_inventory_product
        FOREIGN KEY (product_id)
            REFERENCES products(id)
            ON DELETE RESTRICT,

    CONSTRAINT uq_inventory_idempotency
        UNIQUE (idempotency_key),

    CONSTRAINT uq_inventory_order_product
        UNIQUE (order_id, product_id)
);

ALTER TABLE inventory_reservations
    ADD CONSTRAINT chk_inventory_status
        CHECK (status IN ('RESERVED', 'RELEASED', 'PURCHASED'));

CREATE INDEX idx_inventory_product_id
    ON inventory_reservations(product_id);

CREATE INDEX idx_inventory_order_id
    ON inventory_reservations(order_id);

CREATE INDEX idx_inventory_status
    ON inventory_reservations(status);
