CREATE TABLE orders
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    status        VARCHAR(20)                             NOT NULL,

    total_amount  NUMERIC(12, 2)                          NOT NULL CHECK ( total_amount >= 0 ),
    currency_code VARCHAR(3)                              NOT NULL CHECK ( char_length(currency_code) = 3 ),

    version       BIGINT                                  NOT NULL DEFAULT 0,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),

    CONSTRAINT pk_orders PRIMARY KEY (id),

    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE RESTRICT
);

ALTER TABLE orders
    ADD CONSTRAINT chk_order_status
        CHECK ( status IN ('PENDING', 'CONFIRMED'));

CREATE UNIQUE INDEX uq_one_pending_order_per_user
    ON orders (user_id)
    WHERE status = 'PENDING';

CREATE TABLE order_items
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id              BIGINT                                  NOT NULL,
    product_id            BIGINT                                  NOT NULL,

    product_name_snapshot VARCHAR(255)                            NOT NULL,
    unit_price_snapshot   NUMERIC(19, 2)                          NOT NULL CHECK ( unit_price_snapshot >= 0 ),

    quantity              INTEGER                                 NOT NULL CHECK ( quantity > 0 ),
    line_total            NUMERIC(19, 2)                          NOT NULL CHECK ( line_total >= 0 ),

    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),
    updated_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),

    CONSTRAINT pk_order_items PRIMARY KEY (id),

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_order_items_order_product
        UNIQUE (order_id, product_id)
);

CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_orders_user_id ON orders(user_id);