ALTER TABLE carts
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

-- ----------------------------
-- 1. Orders Table
-- ----------------------------
CREATE TABLE orders
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    status          VARCHAR(20)                             NOT NULL,
    total_amount    NUMERIC(19, 2)                          NOT NULL CHECK ( total_amount >= 0 ),
    idempotency_key VARCHAR(100)                            NOT NULL,
    version         BIGINT                                  NOT NULL DEFAULT 0,

    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),

    CONSTRAINT pk_orders PRIMARY KEY (id),

    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE RESTRICT,

    CONSTRAINT uq_orders_idempotency
        UNIQUE (idempotency_key)
);

-- Order lifecycle constraint
ALTER TABLE orders
    ADD CONSTRAINT chk_orders_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED'));

-- Index for fetching user order history
CREATE INDEX idx_orders_user_id
    ON orders (user_id);

-- ----------------------------
-- 2. Order Items Table
-- ----------------------------
CREATE TABLE order_items
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id              BIGINT                                  NOT NULL,
    product_id            BIGINT                                  NOT NULL,
    product_name_snapshot VARCHAR(255)                            NOT NULL,
    unit_price_snapshot   NUMERIC(19, 2)                          NOT NULL CHECK ( unit_price_snapshot > 0 ),
    quantity              INTEGER                                 NOT NULL CHECK ( quantity > 0 ),

    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),
    updated_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),

    CONSTRAINT pk_order_items PRIMARY KEY (id),

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
            REFERENCES orders (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
            ON DELETE RESTRICT
);

-- Index for loading items by order quickly
CREATE INDEX idx_order_items_order_id
    ON order_items (order_id);

-- Index for product analytics
CREATE INDEX idx_order_items_product_id
    ON order_items (product_id);

-- ----------------------------
-- 3. Inventory Reservation FK Upgrade
-- ----------------------------
-- Now that orders exist, enforce referential integrity

ALTER TABLE inventory_reservations
    ADD CONSTRAINT fk_inventory_order
        FOREIGN KEY (order_id)
            REFERENCES orders (id)
            ON DELETE CASCADE;

