CREATE TABLE inventory_reservations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    cart_id    BIGINT                                  NOT NULL,
    order_id   BIGINT,
    product_id BIGINT                                  NOT NULL,
    quantity   INTEGER                                 NOT NULL CHECK ( quantity > 0 ),
    status     VARCHAR(20)                             NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    version    BIGINT                                  NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),

    CONSTRAINT pk_inventory_reservations PRIMARY KEY (id),

    CONSTRAINT fk_inventory_reservations_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_inventory_reservations_cart
        FOREIGN KEY (cart_id)
            REFERENCES carts (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_inventory_reservations_order
        FOREIGN KEY (order_id)
            REFERENCES orders (id)
            ON DELETE SET NULL,

    CONSTRAINT fk_inventory_reservations_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
            ON DELETE RESTRICT
);

ALTER TABLE inventory_reservations
    ADD CONSTRAINT chk_inventory_reservation_status
        CHECK ( status IN ('ACTIVE', 'CONSUMED', 'EXPIRED', 'CANCELLED'));

CREATE INDEX idx_inventory_reservations_product_status
    ON inventory_reservations (product_id, status);

CREATE INDEX idx_inventory_reservations_expires_at
    ON inventory_reservations (expires_at);

CREATE INDEX idx_inventory_reservations_cart_id
    ON inventory_reservations (cart_id);

CREATE INDEX idx_inventory_reservations_order_id
    ON inventory_reservations (order_id);
